LOGGING:  # configures: dane_workflows.base_util
  NAME : daan-asr-aws
  LEVEL: DEBUG
  DIR: logs  # where to store log files
TASK_SCHEDULER:  # configures: dane_workflows.task_scheduler
  BATCH_PREFIX: your_test  # used to track different iterations of DataProvider.get_next_batch
  BATCH_SIZE: 5  # number of items returned by DataProvider.get_next_batch
  BATCH_LIMIT: -1 # limit of batches to process (-1 for no limit)
  MONITOR_FREQ: -1  # after each n batches call the STATUS_MONITOR
DATA_PROVIDER:  # configures: ExampleDataProvider
  TYPE: ExampleDataProvider
  CONFIG: 
    SOURCE_BATCH_SIZE: 10
EXPORTER:
  TYPE: ExampleExporter
STATUS_HANDLER:
  TYPE: ExampleStatusHandler
STATUS_MONITOR:  # optional, for monitoring 
  TYPE: ExampleStatusMonitor
  CONFIG:
    INCLUDE_EXTRA_INFO: False
PROC_ENV:
  TYPE: ExampleDataProcessingEnvironment
