# Modified from https://jacobian.org/til/github-actions-poetry/
# Run this job on pushes, except to `main`, and for pull requests. I

on:
  push:
    paths-ignore:
      - Dockerfile
      - .dockerignore
      - ./*.yaml
      - README.md
      - LICENSE
  pull_request:

jobs:
  test:
    name: test, lint, type check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: "Install poetry"
      run: "pip install --user poetry"
    - name: "Install this workflow"
      run: " poetry install --no-interaction --no-ansi"
    - name: Run check-project.sh
      run: poetry run scripts/check-project.sh